version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: always
    ports: ["27017:27017"]
    volumes:
      - ./data/mongo:/data/db

  server:
    build: ./server
    environment:
      - MONGO_URI=mongodb://mongo:27017/pg_pms
      - JWT_SECRET=${JWT_SECRET:-please-change-this-secret-in-production}
      - CORS_ORIGIN=http://localhost:5173
    ports: ["4000:4000"]
    depends_on: [mongo]
    volumes:
      - ./server:/app
    command: npm run dev

  client:
    build: ./client
    environment:
      - VITE_API=http://localhost:4000/api
    ports: ["5173:5173"]
    depends_on: [server]
    volumes:
      - ./client:/app
    command: npm run dev
