version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: always
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/pg_pms
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - PORT=4000
    ports: ["4000:4000"]
    depends_on: [mongo]
    volumes:
      - server_uploads:/app/uploads

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    restart: always
    environment:
      - VITE_API=${VITE_API}
    ports: ["80:80"]
    depends_on: [server]

volumes:
  mongo_data:
  server_uploads:
